# Generated by Django 4.2.25 on 2025-10-31 08:10

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0002_users_alter_tasks_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
