# Generated by Django 4.2.25 on 2025-10-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0003_alter_users_password_alter_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
