# Generated by Django 4.2.25 on 2025-10-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_alter_users_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=30),
        ),
    ]
